### ISSUE TITLE
Menu options for all of the users

### ISSUE THREAD

**Issue by Albvadi** [QuickBox/quickbox_dashboard#8]
Hi,
first of all, thanks for this awesome project!

I had installed Plex and NextCloud trough the dashboard and works well.
But the option in the left panel only shows for the admin user, not for all of the users..

I view the condition in the code: `<?php if ($username == "$master") { ?>`

Would not be better show the apps to all of the users?? Or create settings to assign options menu to other users??

Thanks!

**Comment by JMSDOnline** [comment]
> Would not be better show the apps to all of the users?? Or create settings to assign options menu to other users??

Each created user receives their own dashboard. Showing all apps is not an option currently present in QuickBox as multi-user is merely an added courtesy. Some of these apps (such as Plex) are exclusive only to the master user of the account.. therefore, there is no reason other users should see this. We are currently working on a new version of QuickBox that handles applications via docker containers, then we may have these options available.

#### Post Script:
If you remove the wrapped `if` statement around some of these items you may invite users to install/uninstall applications and cause issues on your server... it is heavily advised against.
